# Welcome to Jekyll!

# Website settings
title: "Luis Toro Encina"
description: "Website based on Jack's blog,use Jekyll and github pages."
keywords: "Brandon,blog,Jekyll,github,gh-pages"
baseurl: "/"
url: "lgtoroe.gitHub.io"
# url: "http://127.0.0.1:4000"

# author
author:
  name: 'Luis'
  first_name: 'Luis'
  last_name: 'Toro'
  email: 'lgtoroe@gmail.com'
  facebook_username: 'luis.toro.encina'
  linkedin_username: 'luis-guillermo-toro-encina-9b87a256'
  github_username: 'lgtoroe'
  head_img: 'static/img/landing/luis.jpg'
  desc: 'I am an electrical and electronic engineer who is self-motivated and passionate about learning, i have dedicated my professional life to computer engineering with high knowledge in Software and Hardware in positions such as Datacenter Operator, SAP Administrator, Backup Engineer and last year as DevOPS. . I love to engage with people and through all of my experiences I have gained a thirst for knowledge, a constant desire for self-improvement, and the drive to be a leader.' 
# sections
sections:
  - id: 'about-me'
    i18n: 'nav.about_me'
    name: 'Home'
    tpl: 'about.html'
    css: ''

  # - id: 'career'
  #   i18n: 'nav.career'
  #   name: 'Career'
  #   tpl: 'career.html'
  #   css: 'timeline'

  # - id: 'skills'
  #   i18n: 'nav.skills'
  #   name: 'Skills'
  #   tpl: 'skills.html'
  #   css: 'team'

  # - id: 'projects'
  #   i18n: 'nav.projects'
  #   name: 'Projects'
  #   tpl: 'projects.html'
  #   css: 'project'

  - id: 'links'
    tpl: 'links.html'
    css: 'contact'

# localization
languages:
  - locale: 'es'
    flag: 'static/img/flags/Spain.png'
  - locale: 'cl'
    flag: 'static/img/flags/Chile.png'

# blog img path
img_path: 'http://lgtoroe.github.io/static/img/blog'

# donate
donate:
  wechat: 'static/img/pay/wechat.png'
  alipay: 'static/img/pay/alipay.png'

# comment
changyan:
  # appid: cysfY7ULn
  # conf: prod_861928934cecb7a18e15bedaed9dae29
disqus:
  # name: jalpc
  # public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7

# share
bshare:
  # uuid: 513f778e-a8f7-4c20-9ec2-d29cc2328d75

# baidu analytics
ba:
  # uuid: 317acca9ef9255b934e46371e471431d

# google analytics
ga:
  # id: UA-73784599-1

# growingIO
gio:
  # id: a49d4901c7853da9

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
